lr: 0.0001
lr_step: 20
phase: predict
augmentation: r
extra: corner_edge
batch_size: 4
val_interval: 1
num_epochs: 35
visualize_iter: 5
use_cuda: False
decay_rate: 0
im_size: 256
seed: 12138
resume: False
model_path: C:/Project/floor-sp/floor-sp/mains/FloorPlotter_weights/corner_edge_module/checkpoint_corner_edge_34.pth.tar
dump_prediction: True
exp_base_dir: ./results_corner
data_dir: ../data/dataset_corner
